#include "declarations.h"

void __declspec(naked) h_D3DXAssembleShader() { _asm{ jmp p_D3DXAssembleShader } }
void __declspec(naked) h_D3DXAssembleShaderFromFileA() { _asm{ jmp p_D3DXAssembleShaderFromFileA } }
void __declspec(naked) h_D3DXAssembleShaderFromFileW() { _asm{ jmp p_D3DXAssembleShaderFromFileW } }
void __declspec(naked) h_D3DXAssembleShaderFromResourceA() { _asm{ jmp p_D3DXAssembleShaderFromResourceA } }
void __declspec(naked) h_D3DXAssembleShaderFromResourceW() { _asm{ jmp p_D3DXAssembleShaderFromResourceW } }
void __declspec(naked) h_D3DXBoxBoundProbe() { _asm{ jmp p_D3DXBoxBoundProbe } }
void __declspec(naked) h_D3DXCheckCubeTextureRequirements() { _asm{ jmp p_D3DXCheckCubeTextureRequirements } }
void __declspec(naked) h_D3DXCheckTextureRequirements() { _asm{ jmp p_D3DXCheckTextureRequirements } }
void __declspec(naked) h_D3DXCheckVersion() { _asm{ jmp p_D3DXCheckVersion } }
void __declspec(naked) h_D3DXCheckVolumeTextureRequirements() { _asm{ jmp p_D3DXCheckVolumeTextureRequirements } }
void __declspec(naked) h_D3DXCleanMesh() { _asm{ jmp p_D3DXCleanMesh } }
void __declspec(naked) h_D3DXColorAdjustContrast() { _asm{ jmp p_D3DXColorAdjustContrast } }
void __declspec(naked) h_D3DXColorAdjustSaturation() { _asm{ jmp p_D3DXColorAdjustSaturation } }
void __declspec(naked) h_D3DXCompileShader() { _asm{ jmp p_D3DXCompileShader } }
void __declspec(naked) h_D3DXCompileShaderFromFileA() { _asm{ jmp p_D3DXCompileShaderFromFileA } }
void __declspec(naked) h_D3DXCompileShaderFromFileW() { _asm{ jmp p_D3DXCompileShaderFromFileW } }
void __declspec(naked) h_D3DXCompileShaderFromResourceA() { _asm{ jmp p_D3DXCompileShaderFromResourceA } }
void __declspec(naked) h_D3DXCompileShaderFromResourceW() { _asm{ jmp p_D3DXCompileShaderFromResourceW } }
void __declspec(naked) h_D3DXComputeBoundingBox() { _asm{ jmp p_D3DXComputeBoundingBox } }
void __declspec(naked) h_D3DXComputeBoundingSphere() { _asm{ jmp p_D3DXComputeBoundingSphere } }
void __declspec(naked) h_D3DXComputeIMTFromPerTexelSignal() { _asm{ jmp p_D3DXComputeIMTFromPerTexelSignal } }
void __declspec(naked) h_D3DXComputeIMTFromPerVertexSignal() { _asm{ jmp p_D3DXComputeIMTFromPerVertexSignal } }
void __declspec(naked) h_D3DXComputeIMTFromSignal() { _asm{ jmp p_D3DXComputeIMTFromSignal } }
void __declspec(naked) h_D3DXComputeIMTFromTexture() { _asm{ jmp p_D3DXComputeIMTFromTexture } }
void __declspec(naked) h_D3DXComputeNormalMap() { _asm{ jmp p_D3DXComputeNormalMap } }
void __declspec(naked) h_D3DXComputeNormals() { _asm{ jmp p_D3DXComputeNormals } }
void __declspec(naked) h_D3DXComputeTangent() { _asm{ jmp p_D3DXComputeTangent } }
void __declspec(naked) h_D3DXComputeTangentFrame() { _asm{ jmp p_D3DXComputeTangentFrame } }
void __declspec(naked) h_D3DXComputeTangentFrameEx() { _asm{ jmp p_D3DXComputeTangentFrameEx } }
void __declspec(naked) h_D3DXConcatenateMeshes() { _asm{ jmp p_D3DXConcatenateMeshes } }
void __declspec(naked) h_D3DXConvertMeshSubsetToSingleStrip() { _asm{ jmp p_D3DXConvertMeshSubsetToSingleStrip } }
void __declspec(naked) h_D3DXConvertMeshSubsetToStrips() { _asm{ jmp p_D3DXConvertMeshSubsetToStrips } }
void __declspec(naked) h_D3DXCreateAnimationController() { _asm{ jmp p_D3DXCreateAnimationController } }
void __declspec(naked) h_D3DXCreateBox() { _asm{ jmp p_D3DXCreateBox } }
void __declspec(naked) h_D3DXCreateBuffer() { _asm{ jmp p_D3DXCreateBuffer } }
void __declspec(naked) h_D3DXCreateCompressedAnimationSet() { _asm{ jmp p_D3DXCreateCompressedAnimationSet } }
void __declspec(naked) h_D3DXCreateCubeTexture() { _asm{ jmp p_D3DXCreateCubeTexture } }
void __declspec(naked) h_D3DXCreateCubeTextureFromFileA() { _asm{ jmp p_D3DXCreateCubeTextureFromFileA } }
void __declspec(naked) h_D3DXCreateCubeTextureFromFileExA() { _asm{ jmp p_D3DXCreateCubeTextureFromFileExA } }
void __declspec(naked) h_D3DXCreateCubeTextureFromFileExW() { _asm{ jmp p_D3DXCreateCubeTextureFromFileExW } }
void __declspec(naked) h_D3DXCreateCubeTextureFromFileInMemory() { _asm{ jmp p_D3DXCreateCubeTextureFromFileInMemory } }
void __declspec(naked) h_D3DXCreateCubeTextureFromFileInMemoryEx() { _asm{ jmp p_D3DXCreateCubeTextureFromFileInMemoryEx } }
void __declspec(naked) h_D3DXCreateCubeTextureFromFileW() { _asm{ jmp p_D3DXCreateCubeTextureFromFileW } }
void __declspec(naked) h_D3DXCreateCubeTextureFromResourceA() { _asm{ jmp p_D3DXCreateCubeTextureFromResourceA } }
void __declspec(naked) h_D3DXCreateCubeTextureFromResourceExA() { _asm{ jmp p_D3DXCreateCubeTextureFromResourceExA } }
void __declspec(naked) h_D3DXCreateCubeTextureFromResourceExW() { _asm{ jmp p_D3DXCreateCubeTextureFromResourceExW } }
void __declspec(naked) h_D3DXCreateCubeTextureFromResourceW() { _asm{ jmp p_D3DXCreateCubeTextureFromResourceW } }
void __declspec(naked) h_D3DXCreateCylinder() { _asm{ jmp p_D3DXCreateCylinder } }
void __declspec(naked) h_D3DXCreateEffect() { _asm{ jmp p_D3DXCreateEffect } }
void __declspec(naked) h_D3DXCreateEffectCompiler() { _asm{ jmp p_D3DXCreateEffectCompiler } }
void __declspec(naked) h_D3DXCreateEffectCompilerFromFileA() { _asm{ jmp p_D3DXCreateEffectCompilerFromFileA } }
void __declspec(naked) h_D3DXCreateEffectCompilerFromFileW() { _asm{ jmp p_D3DXCreateEffectCompilerFromFileW } }
void __declspec(naked) h_D3DXCreateEffectCompilerFromResourceA() { _asm{ jmp p_D3DXCreateEffectCompilerFromResourceA } }
void __declspec(naked) h_D3DXCreateEffectCompilerFromResourceW() { _asm{ jmp p_D3DXCreateEffectCompilerFromResourceW } }
void __declspec(naked) h_D3DXCreateEffectEx() { _asm{ jmp p_D3DXCreateEffectEx } }
void __declspec(naked) h_D3DXCreateEffectFromFileA() { _asm{ jmp p_D3DXCreateEffectFromFileA } }
void __declspec(naked) h_D3DXCreateEffectFromFileExA() { _asm{ jmp p_D3DXCreateEffectFromFileExA } }
void __declspec(naked) h_D3DXCreateEffectFromFileExW() { _asm{ jmp p_D3DXCreateEffectFromFileExW } }
void __declspec(naked) h_D3DXCreateEffectFromFileW() { _asm{ jmp p_D3DXCreateEffectFromFileW } }
void __declspec(naked) h_D3DXCreateEffectFromResourceA() { _asm{ jmp p_D3DXCreateEffectFromResourceA } }
void __declspec(naked) h_D3DXCreateEffectFromResourceExA() { _asm{ jmp p_D3DXCreateEffectFromResourceExA } }
void __declspec(naked) h_D3DXCreateEffectFromResourceExW() { _asm{ jmp p_D3DXCreateEffectFromResourceExW } }
void __declspec(naked) h_D3DXCreateEffectFromResourceW() { _asm{ jmp p_D3DXCreateEffectFromResourceW } }
void __declspec(naked) h_D3DXCreateEffectPool() { _asm{ jmp p_D3DXCreateEffectPool } }
void __declspec(naked) h_D3DXCreateFontA() { _asm{ jmp p_D3DXCreateFontA } }
void __declspec(naked) h_D3DXCreateFontIndirectA() { _asm{ jmp p_D3DXCreateFontIndirectA } }
void __declspec(naked) h_D3DXCreateFontIndirectW() { _asm{ jmp p_D3DXCreateFontIndirectW } }
void __declspec(naked) h_D3DXCreateFontW() { _asm{ jmp p_D3DXCreateFontW } }
void __declspec(naked) h_D3DXCreateFragmentLinker() { _asm{ jmp p_D3DXCreateFragmentLinker } }
void __declspec(naked) h_D3DXCreateKeyframedAnimationSet() { _asm{ jmp p_D3DXCreateKeyframedAnimationSet } }
void __declspec(naked) h_D3DXCreateLine() { _asm{ jmp p_D3DXCreateLine } }
void __declspec(naked) h_D3DXCreateMatrixStack() { _asm{ jmp p_D3DXCreateMatrixStack } }
void __declspec(naked) h_D3DXCreateMesh() { _asm{ jmp p_D3DXCreateMesh } }
void __declspec(naked) h_D3DXCreateMeshFVF() { _asm{ jmp p_D3DXCreateMeshFVF } }
void __declspec(naked) h_D3DXCreateNPatchMesh() { _asm{ jmp p_D3DXCreateNPatchMesh } }
void __declspec(naked) h_D3DXCreatePMeshFromStream() { _asm{ jmp p_D3DXCreatePMeshFromStream } }
void __declspec(naked) h_D3DXCreatePRTBuffer() { _asm{ jmp p_D3DXCreatePRTBuffer } }
void __declspec(naked) h_D3DXCreatePRTBufferTex() { _asm{ jmp p_D3DXCreatePRTBufferTex } }
void __declspec(naked) h_D3DXCreatePRTCompBuffer() { _asm{ jmp p_D3DXCreatePRTCompBuffer } }
void __declspec(naked) h_D3DXCreatePRTEngine() { _asm{ jmp p_D3DXCreatePRTEngine } }
void __declspec(naked) h_D3DXCreatePatchMesh() { _asm{ jmp p_D3DXCreatePatchMesh } }
void __declspec(naked) h_D3DXCreatePolygon() { _asm{ jmp p_D3DXCreatePolygon } }
void __declspec(naked) h_D3DXCreateRenderToEnvMap() { _asm{ jmp p_D3DXCreateRenderToEnvMap } }
void __declspec(naked) h_D3DXCreateRenderToSurface() { _asm{ jmp p_D3DXCreateRenderToSurface } }
void __declspec(naked) h_D3DXCreateSPMesh() { _asm{ jmp p_D3DXCreateSPMesh } }
void __declspec(naked) h_D3DXCreateSkinInfo() { _asm{ jmp p_D3DXCreateSkinInfo } }
void __declspec(naked) h_D3DXCreateSkinInfoFVF() { _asm{ jmp p_D3DXCreateSkinInfoFVF } }
void __declspec(naked) h_D3DXCreateSkinInfoFromBlendedMesh() { _asm{ jmp p_D3DXCreateSkinInfoFromBlendedMesh } }
void __declspec(naked) h_D3DXCreateSphere() { _asm{ jmp p_D3DXCreateSphere } }
void __declspec(naked) h_D3DXCreateSprite() { _asm{ jmp p_D3DXCreateSprite } }
void __declspec(naked) h_D3DXCreateTeapot() { _asm{ jmp p_D3DXCreateTeapot } }
void __declspec(naked) h_D3DXCreateTextA() { _asm{ jmp p_D3DXCreateTextA } }
void __declspec(naked) h_D3DXCreateTextW() { _asm{ jmp p_D3DXCreateTextW } }
void __declspec(naked) h_D3DXCreateTexture() { _asm{ jmp p_D3DXCreateTexture } }
void __declspec(naked) h_D3DXCreateTextureFromFileA() { _asm{ jmp p_D3DXCreateTextureFromFileA } }
void __declspec(naked) h_D3DXCreateTextureFromFileExA() { _asm{ jmp p_D3DXCreateTextureFromFileExA } }
void __declspec(naked) h_D3DXCreateTextureFromFileExW() { _asm{ jmp p_D3DXCreateTextureFromFileExW } }
void __declspec(naked) h_D3DXCreateTextureFromFileInMemory() { _asm{ jmp p_D3DXCreateTextureFromFileInMemory } }
void __declspec(naked) h_D3DXCreateTextureFromFileInMemoryEx() { _asm{ jmp p_D3DXCreateTextureFromFileInMemoryEx } }
void __declspec(naked) h_D3DXCreateTextureFromFileW() { _asm{ jmp p_D3DXCreateTextureFromFileW } }
void __declspec(naked) h_D3DXCreateTextureFromResourceA() { _asm{ jmp p_D3DXCreateTextureFromResourceA } }
void __declspec(naked) h_D3DXCreateTextureFromResourceExA() { _asm{ jmp p_D3DXCreateTextureFromResourceExA } }
void __declspec(naked) h_D3DXCreateTextureFromResourceExW() { _asm{ jmp p_D3DXCreateTextureFromResourceExW } }
void __declspec(naked) h_D3DXCreateTextureFromResourceW() { _asm{ jmp p_D3DXCreateTextureFromResourceW } }
void __declspec(naked) h_D3DXCreateTextureGutterHelper() { _asm{ jmp p_D3DXCreateTextureGutterHelper } }
void __declspec(naked) h_D3DXCreateTextureShader() { _asm{ jmp p_D3DXCreateTextureShader } }
void __declspec(naked) h_D3DXCreateTorus() { _asm{ jmp p_D3DXCreateTorus } }
void __declspec(naked) h_D3DXCreateVolumeTexture() { _asm{ jmp p_D3DXCreateVolumeTexture } }
void __declspec(naked) h_D3DXCreateVolumeTextureFromFileA() { _asm{ jmp p_D3DXCreateVolumeTextureFromFileA } }
void __declspec(naked) h_D3DXCreateVolumeTextureFromFileExA() { _asm{ jmp p_D3DXCreateVolumeTextureFromFileExA } }
void __declspec(naked) h_D3DXCreateVolumeTextureFromFileExW() { _asm{ jmp p_D3DXCreateVolumeTextureFromFileExW } }
void __declspec(naked) h_D3DXCreateVolumeTextureFromFileInMemory() { _asm{ jmp p_D3DXCreateVolumeTextureFromFileInMemory } }
void __declspec(naked) h_D3DXCreateVolumeTextureFromFileInMemoryEx() { _asm{ jmp p_D3DXCreateVolumeTextureFromFileInMemoryEx } }
void __declspec(naked) h_D3DXCreateVolumeTextureFromFileW() { _asm{ jmp p_D3DXCreateVolumeTextureFromFileW } }
void __declspec(naked) h_D3DXCreateVolumeTextureFromResourceA() { _asm{ jmp p_D3DXCreateVolumeTextureFromResourceA } }
void __declspec(naked) h_D3DXCreateVolumeTextureFromResourceExA() { _asm{ jmp p_D3DXCreateVolumeTextureFromResourceExA } }
void __declspec(naked) h_D3DXCreateVolumeTextureFromResourceExW() { _asm{ jmp p_D3DXCreateVolumeTextureFromResourceExW } }
void __declspec(naked) h_D3DXCreateVolumeTextureFromResourceW() { _asm{ jmp p_D3DXCreateVolumeTextureFromResourceW } }
void __declspec(naked) h_D3DXDebugMute() { _asm{ jmp p_D3DXDebugMute } }
void __declspec(naked) h_D3DXDeclaratorFromFVF() { _asm{ jmp p_D3DXDeclaratorFromFVF } }
void __declspec(naked) h_D3DXDisassembleEffect() { _asm{ jmp p_D3DXDisassembleEffect } }
void __declspec(naked) h_D3DXDisassembleShader() { _asm{ jmp p_D3DXDisassembleShader } }
void __declspec(naked) h_D3DXFVFFromDeclarator() { _asm{ jmp p_D3DXFVFFromDeclarator } }
void __declspec(naked) h_D3DXFileCreate() { _asm{ jmp p_D3DXFileCreate } }
void __declspec(naked) h_D3DXFillCubeTexture() { _asm{ jmp p_D3DXFillCubeTexture } }
void __declspec(naked) h_D3DXFillCubeTextureTX() { _asm{ jmp p_D3DXFillCubeTextureTX } }
void __declspec(naked) h_D3DXFillTexture() { _asm{ jmp p_D3DXFillTexture } }
void __declspec(naked) h_D3DXFillTextureTX() { _asm{ jmp p_D3DXFillTextureTX } }
void __declspec(naked) h_D3DXFillVolumeTexture() { _asm{ jmp p_D3DXFillVolumeTexture } }
void __declspec(naked) h_D3DXFillVolumeTextureTX() { _asm{ jmp p_D3DXFillVolumeTextureTX } }
void __declspec(naked) h_D3DXFilterTexture() { _asm{ jmp p_D3DXFilterTexture } }
void __declspec(naked) h_D3DXFindShaderComment() { _asm{ jmp p_D3DXFindShaderComment } }
void __declspec(naked) h_D3DXFloat16To32Array() { _asm{ jmp p_D3DXFloat16To32Array } }
void __declspec(naked) h_D3DXFloat32To16Array() { _asm{ jmp p_D3DXFloat32To16Array } }
void __declspec(naked) h_D3DXFrameAppendChild() { _asm{ jmp p_D3DXFrameAppendChild } }
void __declspec(naked) h_D3DXFrameCalculateBoundingSphere() { _asm{ jmp p_D3DXFrameCalculateBoundingSphere } }
void __declspec(naked) h_D3DXFrameDestroy() { _asm{ jmp p_D3DXFrameDestroy } }
void __declspec(naked) h_D3DXFrameFind() { _asm{ jmp p_D3DXFrameFind } }
void __declspec(naked) h_D3DXFrameNumNamedMatrices() { _asm{ jmp p_D3DXFrameNumNamedMatrices } }
void __declspec(naked) h_D3DXFrameRegisterNamedMatrices() { _asm{ jmp p_D3DXFrameRegisterNamedMatrices } }
void __declspec(naked) h_D3DXFresnelTerm() { _asm{ jmp p_D3DXFresnelTerm } }
void __declspec(naked) h_D3DXGatherFragments() { _asm{ jmp p_D3DXGatherFragments } }
void __declspec(naked) h_D3DXGatherFragmentsFromFileA() { _asm{ jmp p_D3DXGatherFragmentsFromFileA } }
void __declspec(naked) h_D3DXGatherFragmentsFromFileW() { _asm{ jmp p_D3DXGatherFragmentsFromFileW } }
void __declspec(naked) h_D3DXGatherFragmentsFromResourceA() { _asm{ jmp p_D3DXGatherFragmentsFromResourceA } }
void __declspec(naked) h_D3DXGatherFragmentsFromResourceW() { _asm{ jmp p_D3DXGatherFragmentsFromResourceW } }
void __declspec(naked) h_D3DXGenerateOutputDecl() { _asm{ jmp p_D3DXGenerateOutputDecl } }
void __declspec(naked) h_D3DXGeneratePMesh() { _asm{ jmp p_D3DXGeneratePMesh } }
void __declspec(naked) h_D3DXGetDeclLength() { _asm{ jmp p_D3DXGetDeclLength } }
void __declspec(naked) h_D3DXGetDeclVertexSize() { _asm{ jmp p_D3DXGetDeclVertexSize } }
void __declspec(naked) h_D3DXGetDriverLevel() { _asm{ jmp p_D3DXGetDriverLevel } }
void __declspec(naked) h_D3DXGetFVFVertexSize() { _asm{ jmp p_D3DXGetFVFVertexSize } }
void __declspec(naked) h_D3DXGetImageInfoFromFileA() { _asm{ jmp p_D3DXGetImageInfoFromFileA } }
void __declspec(naked) h_D3DXGetImageInfoFromFileInMemory() { _asm{ jmp p_D3DXGetImageInfoFromFileInMemory } }
void __declspec(naked) h_D3DXGetImageInfoFromFileW() { _asm{ jmp p_D3DXGetImageInfoFromFileW } }
void __declspec(naked) h_D3DXGetImageInfoFromResourceA() { _asm{ jmp p_D3DXGetImageInfoFromResourceA } }
void __declspec(naked) h_D3DXGetImageInfoFromResourceW() { _asm{ jmp p_D3DXGetImageInfoFromResourceW } }
void __declspec(naked) h_D3DXGetPixelShaderProfile() { _asm{ jmp p_D3DXGetPixelShaderProfile } }
void __declspec(naked) h_D3DXGetShaderConstantTable() { _asm{ jmp p_D3DXGetShaderConstantTable } }
void __declspec(naked) h_D3DXGetShaderInputSemantics() { _asm{ jmp p_D3DXGetShaderInputSemantics } }
void __declspec(naked) h_D3DXGetShaderOutputSemantics() { _asm{ jmp p_D3DXGetShaderOutputSemantics } }
void __declspec(naked) h_D3DXGetShaderSamplers() { _asm{ jmp p_D3DXGetShaderSamplers } }
void __declspec(naked) h_D3DXGetShaderSize() { _asm{ jmp p_D3DXGetShaderSize } }
void __declspec(naked) h_D3DXGetShaderVersion() { _asm{ jmp p_D3DXGetShaderVersion } }
void __declspec(naked) h_D3DXGetVertexShaderProfile() { _asm{ jmp p_D3DXGetVertexShaderProfile } }
void __declspec(naked) h_D3DXIntersect() { _asm{ jmp p_D3DXIntersect } }
void __declspec(naked) h_D3DXIntersectSubset() { _asm{ jmp p_D3DXIntersectSubset } }
void __declspec(naked) h_D3DXIntersectTri() { _asm{ jmp p_D3DXIntersectTri } }
void __declspec(naked) h_D3DXLoadMeshFromXA() { _asm{ jmp p_D3DXLoadMeshFromXA } }
void __declspec(naked) h_D3DXLoadMeshFromXInMemory() { _asm{ jmp p_D3DXLoadMeshFromXInMemory } }
void __declspec(naked) h_D3DXLoadMeshFromXResource() { _asm{ jmp p_D3DXLoadMeshFromXResource } }
void __declspec(naked) h_D3DXLoadMeshFromXW() { _asm{ jmp p_D3DXLoadMeshFromXW } }
void __declspec(naked) h_D3DXLoadMeshFromXof() { _asm{ jmp p_D3DXLoadMeshFromXof } }
void __declspec(naked) h_D3DXLoadMeshHierarchyFromXA() { _asm{ jmp p_D3DXLoadMeshHierarchyFromXA } }
void __declspec(naked) h_D3DXLoadMeshHierarchyFromXInMemory() { _asm{ jmp p_D3DXLoadMeshHierarchyFromXInMemory } }
void __declspec(naked) h_D3DXLoadMeshHierarchyFromXW() { _asm{ jmp p_D3DXLoadMeshHierarchyFromXW } }
void __declspec(naked) h_D3DXLoadPRTBufferFromFileA() { _asm{ jmp p_D3DXLoadPRTBufferFromFileA } }
void __declspec(naked) h_D3DXLoadPRTBufferFromFileW() { _asm{ jmp p_D3DXLoadPRTBufferFromFileW } }
void __declspec(naked) h_D3DXLoadPRTCompBufferFromFileA() { _asm{ jmp p_D3DXLoadPRTCompBufferFromFileA } }
void __declspec(naked) h_D3DXLoadPRTCompBufferFromFileW() { _asm{ jmp p_D3DXLoadPRTCompBufferFromFileW } }
void __declspec(naked) h_D3DXLoadPatchMeshFromXof() { _asm{ jmp p_D3DXLoadPatchMeshFromXof } }
void __declspec(naked) h_D3DXLoadSkinMeshFromXof() { _asm{ jmp p_D3DXLoadSkinMeshFromXof } }
void __declspec(naked) h_D3DXLoadSurfaceFromFileA() { _asm{ jmp p_D3DXLoadSurfaceFromFileA } }
void __declspec(naked) h_D3DXLoadSurfaceFromFileInMemory() { _asm{ jmp p_D3DXLoadSurfaceFromFileInMemory } }
void __declspec(naked) h_D3DXLoadSurfaceFromFileW() { _asm{ jmp p_D3DXLoadSurfaceFromFileW } }
void __declspec(naked) h_D3DXLoadSurfaceFromMemory() { _asm{ jmp p_D3DXLoadSurfaceFromMemory } }
void __declspec(naked) h_D3DXLoadSurfaceFromResourceA() { _asm{ jmp p_D3DXLoadSurfaceFromResourceA } }
void __declspec(naked) h_D3DXLoadSurfaceFromResourceW() { _asm{ jmp p_D3DXLoadSurfaceFromResourceW } }
void __declspec(naked) h_D3DXLoadSurfaceFromSurface() { _asm{ jmp p_D3DXLoadSurfaceFromSurface } }
void __declspec(naked) h_D3DXLoadVolumeFromFileA() { _asm{ jmp p_D3DXLoadVolumeFromFileA } }
void __declspec(naked) h_D3DXLoadVolumeFromFileInMemory() { _asm{ jmp p_D3DXLoadVolumeFromFileInMemory } }
void __declspec(naked) h_D3DXLoadVolumeFromFileW() { _asm{ jmp p_D3DXLoadVolumeFromFileW } }
void __declspec(naked) h_D3DXLoadVolumeFromMemory() { _asm{ jmp p_D3DXLoadVolumeFromMemory } }
void __declspec(naked) h_D3DXLoadVolumeFromResourceA() { _asm{ jmp p_D3DXLoadVolumeFromResourceA } }
void __declspec(naked) h_D3DXLoadVolumeFromResourceW() { _asm{ jmp p_D3DXLoadVolumeFromResourceW } }
void __declspec(naked) h_D3DXLoadVolumeFromVolume() { _asm{ jmp p_D3DXLoadVolumeFromVolume } }
void __declspec(naked) h_D3DXMatrixAffineTransformation2D() { _asm{ jmp p_D3DXMatrixAffineTransformation2D } }
void __declspec(naked) h_D3DXMatrixAffineTransformation() { _asm{ jmp p_D3DXMatrixAffineTransformation } }
void __declspec(naked) h_D3DXMatrixDecompose() { _asm{ jmp p_D3DXMatrixDecompose } }
void __declspec(naked) h_D3DXMatrixDeterminant() { _asm{ jmp p_D3DXMatrixDeterminant } }
void __declspec(naked) h_D3DXMatrixInverse() { _asm{ jmp p_D3DXMatrixInverse } }
void __declspec(naked) h_D3DXMatrixLookAtLH() { _asm{ jmp p_D3DXMatrixLookAtLH } }
void __declspec(naked) h_D3DXMatrixLookAtRH() { _asm{ jmp p_D3DXMatrixLookAtRH } }
void __declspec(naked) h_D3DXMatrixMultiply() { _asm{ jmp p_D3DXMatrixMultiply } }
void __declspec(naked) h_D3DXMatrixMultiplyTranspose() { _asm{ jmp p_D3DXMatrixMultiplyTranspose } }
void __declspec(naked) h_D3DXMatrixOrthoLH() { _asm{ jmp p_D3DXMatrixOrthoLH } }
void __declspec(naked) h_D3DXMatrixOrthoOffCenterLH() { _asm{ jmp p_D3DXMatrixOrthoOffCenterLH } }
void __declspec(naked) h_D3DXMatrixOrthoOffCenterRH() { _asm{ jmp p_D3DXMatrixOrthoOffCenterRH } }
void __declspec(naked) h_D3DXMatrixOrthoRH() { _asm{ jmp p_D3DXMatrixOrthoRH } }
void __declspec(naked) h_D3DXMatrixPerspectiveFovLH() { _asm{ jmp p_D3DXMatrixPerspectiveFovLH } }
void __declspec(naked) h_D3DXMatrixPerspectiveFovRH() { _asm{ jmp p_D3DXMatrixPerspectiveFovRH } }
void __declspec(naked) h_D3DXMatrixPerspectiveLH() { _asm{ jmp p_D3DXMatrixPerspectiveLH } }
void __declspec(naked) h_D3DXMatrixPerspectiveOffCenterLH() { _asm{ jmp p_D3DXMatrixPerspectiveOffCenterLH } }
void __declspec(naked) h_D3DXMatrixPerspectiveOffCenterRH() { _asm{ jmp p_D3DXMatrixPerspectiveOffCenterRH } }
void __declspec(naked) h_D3DXMatrixPerspectiveRH() { _asm{ jmp p_D3DXMatrixPerspectiveRH } }
void __declspec(naked) h_D3DXMatrixReflect() { _asm{ jmp p_D3DXMatrixReflect } }
void __declspec(naked) h_D3DXMatrixRotationAxis() { _asm{ jmp p_D3DXMatrixRotationAxis } }
void __declspec(naked) h_D3DXMatrixRotationQuaternion() { _asm{ jmp p_D3DXMatrixRotationQuaternion } }
void __declspec(naked) h_D3DXMatrixRotationX() { _asm{ jmp p_D3DXMatrixRotationX } }
void __declspec(naked) h_D3DXMatrixRotationY() { _asm{ jmp p_D3DXMatrixRotationY } }
void __declspec(naked) h_D3DXMatrixRotationYawPitchRoll() { _asm{ jmp p_D3DXMatrixRotationYawPitchRoll } }
void __declspec(naked) h_D3DXMatrixRotationZ() { _asm{ jmp p_D3DXMatrixRotationZ } }
void __declspec(naked) h_D3DXMatrixScaling() { _asm{ jmp p_D3DXMatrixScaling } }
void __declspec(naked) h_D3DXMatrixShadow() { _asm{ jmp p_D3DXMatrixShadow } }
void __declspec(naked) h_D3DXMatrixTransformation2D() { _asm{ jmp p_D3DXMatrixTransformation2D } }
void __declspec(naked) h_D3DXMatrixTransformation() { _asm{ jmp p_D3DXMatrixTransformation } }
void __declspec(naked) h_D3DXMatrixTranslation() { _asm{ jmp p_D3DXMatrixTranslation } }
void __declspec(naked) h_D3DXMatrixTranspose() { _asm{ jmp p_D3DXMatrixTranspose } }
void __declspec(naked) h_D3DXOptimizeFaces() { _asm{ jmp p_D3DXOptimizeFaces } }
void __declspec(naked) h_D3DXOptimizeVertices() { _asm{ jmp p_D3DXOptimizeVertices } }
void __declspec(naked) h_D3DXPlaneFromPointNormal() { _asm{ jmp p_D3DXPlaneFromPointNormal } }
void __declspec(naked) h_D3DXPlaneFromPoints() { _asm{ jmp p_D3DXPlaneFromPoints } }
void __declspec(naked) h_D3DXPlaneIntersectLine() { _asm{ jmp p_D3DXPlaneIntersectLine } }
void __declspec(naked) h_D3DXPlaneNormalize() { _asm{ jmp p_D3DXPlaneNormalize } }
void __declspec(naked) h_D3DXPlaneTransform() { _asm{ jmp p_D3DXPlaneTransform } }
void __declspec(naked) h_D3DXPlaneTransformArray() { _asm{ jmp p_D3DXPlaneTransformArray } }
void __declspec(naked) h_D3DXPreprocessShader() { _asm{ jmp p_D3DXPreprocessShader } }
void __declspec(naked) h_D3DXPreprocessShaderFromFileA() { _asm{ jmp p_D3DXPreprocessShaderFromFileA } }
void __declspec(naked) h_D3DXPreprocessShaderFromFileW() { _asm{ jmp p_D3DXPreprocessShaderFromFileW } }
void __declspec(naked) h_D3DXPreprocessShaderFromResourceA() { _asm{ jmp p_D3DXPreprocessShaderFromResourceA } }
void __declspec(naked) h_D3DXPreprocessShaderFromResourceW() { _asm{ jmp p_D3DXPreprocessShaderFromResourceW } }
void __declspec(naked) h_D3DXQuaternionBaryCentric() { _asm{ jmp p_D3DXQuaternionBaryCentric } }
void __declspec(naked) h_D3DXQuaternionExp() { _asm{ jmp p_D3DXQuaternionExp } }
void __declspec(naked) h_D3DXQuaternionInverse() { _asm{ jmp p_D3DXQuaternionInverse } }
void __declspec(naked) h_D3DXQuaternionLn() { _asm{ jmp p_D3DXQuaternionLn } }
void __declspec(naked) h_D3DXQuaternionMultiply() { _asm{ jmp p_D3DXQuaternionMultiply } }
void __declspec(naked) h_D3DXQuaternionNormalize() { _asm{ jmp p_D3DXQuaternionNormalize } }
void __declspec(naked) h_D3DXQuaternionRotationAxis() { _asm{ jmp p_D3DXQuaternionRotationAxis } }
void __declspec(naked) h_D3DXQuaternionRotationMatrix() { _asm{ jmp p_D3DXQuaternionRotationMatrix } }
void __declspec(naked) h_D3DXQuaternionRotationYawPitchRoll() { _asm{ jmp p_D3DXQuaternionRotationYawPitchRoll } }
void __declspec(naked) h_D3DXQuaternionSlerp() { _asm{ jmp p_D3DXQuaternionSlerp } }
void __declspec(naked) h_D3DXQuaternionSquad() { _asm{ jmp p_D3DXQuaternionSquad } }
void __declspec(naked) h_D3DXQuaternionSquadSetup() { _asm{ jmp p_D3DXQuaternionSquadSetup } }
void __declspec(naked) h_D3DXQuaternionToAxisAngle() { _asm{ jmp p_D3DXQuaternionToAxisAngle } }
void __declspec(naked) h_D3DXRectPatchSize() { _asm{ jmp p_D3DXRectPatchSize } }
void __declspec(naked) h_D3DXSHAdd() { _asm{ jmp p_D3DXSHAdd } }
void __declspec(naked) h_D3DXSHDot() { _asm{ jmp p_D3DXSHDot } }
void __declspec(naked) h_D3DXSHEvalConeLight() { _asm{ jmp p_D3DXSHEvalConeLight } }
void __declspec(naked) h_D3DXSHEvalDirection() { _asm{ jmp p_D3DXSHEvalDirection } }
void __declspec(naked) h_D3DXSHEvalDirectionalLight() { _asm{ jmp p_D3DXSHEvalDirectionalLight } }
void __declspec(naked) h_D3DXSHEvalHemisphereLight() { _asm{ jmp p_D3DXSHEvalHemisphereLight } }
void __declspec(naked) h_D3DXSHEvalSphericalLight() { _asm{ jmp p_D3DXSHEvalSphericalLight } }
void __declspec(naked) h_D3DXSHPRTCompSplitMeshSC() { _asm{ jmp p_D3DXSHPRTCompSplitMeshSC } }
void __declspec(naked) h_D3DXSHPRTCompSuperCluster() { _asm{ jmp p_D3DXSHPRTCompSuperCluster } }
void __declspec(naked) h_D3DXSHProjectCubeMap() { _asm{ jmp p_D3DXSHProjectCubeMap } }
void __declspec(naked) h_D3DXSHRotate() { _asm{ jmp p_D3DXSHRotate } }
void __declspec(naked) h_D3DXSHRotateZ() { _asm{ jmp p_D3DXSHRotateZ } }
void __declspec(naked) h_D3DXSHScale() { _asm{ jmp p_D3DXSHScale } }
void __declspec(naked) h_D3DXSaveMeshHierarchyToFileA() { _asm{ jmp p_D3DXSaveMeshHierarchyToFileA } }
void __declspec(naked) h_D3DXSaveMeshHierarchyToFileW() { _asm{ jmp p_D3DXSaveMeshHierarchyToFileW } }
void __declspec(naked) h_D3DXSaveMeshToXA() { _asm{ jmp p_D3DXSaveMeshToXA } }
void __declspec(naked) h_D3DXSaveMeshToXW() { _asm{ jmp p_D3DXSaveMeshToXW } }
void __declspec(naked) h_D3DXSavePRTBufferToFileA() { _asm{ jmp p_D3DXSavePRTBufferToFileA } }
void __declspec(naked) h_D3DXSavePRTBufferToFileW() { _asm{ jmp p_D3DXSavePRTBufferToFileW } }
void __declspec(naked) h_D3DXSavePRTCompBufferToFileA() { _asm{ jmp p_D3DXSavePRTCompBufferToFileA } }
void __declspec(naked) h_D3DXSavePRTCompBufferToFileW() { _asm{ jmp p_D3DXSavePRTCompBufferToFileW } }
void __declspec(naked) h_D3DXSaveSurfaceToFileA() { _asm{ jmp p_D3DXSaveSurfaceToFileA } }
void __declspec(naked) h_D3DXSaveSurfaceToFileInMemory() { _asm{ jmp p_D3DXSaveSurfaceToFileInMemory } }
void __declspec(naked) h_D3DXSaveSurfaceToFileW() { _asm{ jmp p_D3DXSaveSurfaceToFileW } }
void __declspec(naked) h_D3DXSaveTextureToFileA() { _asm{ jmp p_D3DXSaveTextureToFileA } }
void __declspec(naked) h_D3DXSaveTextureToFileInMemory() { _asm{ jmp p_D3DXSaveTextureToFileInMemory } }
void __declspec(naked) h_D3DXSaveTextureToFileW() { _asm{ jmp p_D3DXSaveTextureToFileW } }
void __declspec(naked) h_D3DXSaveVolumeToFileA() { _asm{ jmp p_D3DXSaveVolumeToFileA } }
void __declspec(naked) h_D3DXSaveVolumeToFileInMemory() { _asm{ jmp p_D3DXSaveVolumeToFileInMemory } }
void __declspec(naked) h_D3DXSaveVolumeToFileW() { _asm{ jmp p_D3DXSaveVolumeToFileW } }
void __declspec(naked) h_D3DXSimplifyMesh() { _asm{ jmp p_D3DXSimplifyMesh } }
void __declspec(naked) h_D3DXSphereBoundProbe() { _asm{ jmp p_D3DXSphereBoundProbe } }
void __declspec(naked) h_D3DXSplitMesh() { _asm{ jmp p_D3DXSplitMesh } }
void __declspec(naked) h_D3DXTessellateNPatches() { _asm{ jmp p_D3DXTessellateNPatches } }
void __declspec(naked) h_D3DXTessellateRectPatch() { _asm{ jmp p_D3DXTessellateRectPatch } }
void __declspec(naked) h_D3DXTessellateTriPatch() { _asm{ jmp p_D3DXTessellateTriPatch } }
void __declspec(naked) h_D3DXTriPatchSize() { _asm{ jmp p_D3DXTriPatchSize } }
void __declspec(naked) h_D3DXUVAtlasCreate() { _asm{ jmp p_D3DXUVAtlasCreate } }
void __declspec(naked) h_D3DXUVAtlasPack() { _asm{ jmp p_D3DXUVAtlasPack } }
void __declspec(naked) h_D3DXUVAtlasPartition() { _asm{ jmp p_D3DXUVAtlasPartition } }
void __declspec(naked) h_D3DXValidMesh() { _asm{ jmp p_D3DXValidMesh } }
void __declspec(naked) h_D3DXValidPatchMesh() { _asm{ jmp p_D3DXValidPatchMesh } }
void __declspec(naked) h_D3DXVec2BaryCentric() { _asm{ jmp p_D3DXVec2BaryCentric } }
void __declspec(naked) h_D3DXVec2CatmullRom() { _asm{ jmp p_D3DXVec2CatmullRom } }
void __declspec(naked) h_D3DXVec2Hermite() { _asm{ jmp p_D3DXVec2Hermite } }
void __declspec(naked) h_D3DXVec2Normalize() { _asm{ jmp p_D3DXVec2Normalize } }
void __declspec(naked) h_D3DXVec2Transform() { _asm{ jmp p_D3DXVec2Transform } }
void __declspec(naked) h_D3DXVec2TransformArray() { _asm{ jmp p_D3DXVec2TransformArray } }
void __declspec(naked) h_D3DXVec2TransformCoord() { _asm{ jmp p_D3DXVec2TransformCoord } }
void __declspec(naked) h_D3DXVec2TransformCoordArray() { _asm{ jmp p_D3DXVec2TransformCoordArray } }
void __declspec(naked) h_D3DXVec2TransformNormal() { _asm{ jmp p_D3DXVec2TransformNormal } }
void __declspec(naked) h_D3DXVec2TransformNormalArray() { _asm{ jmp p_D3DXVec2TransformNormalArray } }
void __declspec(naked) h_D3DXVec3BaryCentric() { _asm{ jmp p_D3DXVec3BaryCentric } }
void __declspec(naked) h_D3DXVec3CatmullRom() { _asm{ jmp p_D3DXVec3CatmullRom } }
void __declspec(naked) h_D3DXVec3Hermite() { _asm{ jmp p_D3DXVec3Hermite } }
void __declspec(naked) h_D3DXVec3Normalize() { _asm{ jmp p_D3DXVec3Normalize } }
void __declspec(naked) h_D3DXVec3Project() { _asm{ jmp p_D3DXVec3Project } }
void __declspec(naked) h_D3DXVec3ProjectArray() { _asm{ jmp p_D3DXVec3ProjectArray } }
void __declspec(naked) h_D3DXVec3Transform() { _asm{ jmp p_D3DXVec3Transform } }
void __declspec(naked) h_D3DXVec3TransformArray() { _asm{ jmp p_D3DXVec3TransformArray } }
void __declspec(naked) h_D3DXVec3TransformCoord() { _asm{ jmp p_D3DXVec3TransformCoord } }
void __declspec(naked) h_D3DXVec3TransformCoordArray() { _asm{ jmp p_D3DXVec3TransformCoordArray } }
void __declspec(naked) h_D3DXVec3TransformNormal() { _asm{ jmp p_D3DXVec3TransformNormal } }
void __declspec(naked) h_D3DXVec3TransformNormalArray() { _asm{ jmp p_D3DXVec3TransformNormalArray } }
void __declspec(naked) h_D3DXVec3Unproject() { _asm{ jmp p_D3DXVec3Unproject } }
void __declspec(naked) h_D3DXVec3UnprojectArray() { _asm{ jmp p_D3DXVec3UnprojectArray } }
void __declspec(naked) h_D3DXVec4BaryCentric() { _asm{ jmp p_D3DXVec4BaryCentric } }
void __declspec(naked) h_D3DXVec4CatmullRom() { _asm{ jmp p_D3DXVec4CatmullRom } }
void __declspec(naked) h_D3DXVec4Cross() { _asm{ jmp p_D3DXVec4Cross } }
void __declspec(naked) h_D3DXVec4Hermite() { _asm{ jmp p_D3DXVec4Hermite } }
void __declspec(naked) h_D3DXVec4Normalize() { _asm{ jmp p_D3DXVec4Normalize } }
void __declspec(naked) h_D3DXVec4Transform() { _asm{ jmp p_D3DXVec4Transform } }
void __declspec(naked) h_D3DXVec4TransformArray() { _asm{ jmp p_D3DXVec4TransformArray } }
void __declspec(naked) h_D3DXWeldVertices() { _asm{ jmp p_D3DXWeldVertices } }
